@startuml

class Магазин{ 
    string Название
    double Доход
}

class Персонал{
    int КоличествоРабочих
    data ФормированиеЧека()

}

class Склад{
    int КоличествоРабочих
    int КоличествоТовара
    data УчетТовара()
}

class Руководство{
    int КоличествоРабочих
    data ПросмотрСтатистики()
}

class Кассир{
    string Фио
    string СменаРаботы
    cash ПриемДенег()
    cash ВозратДенег()
}

class Директор{
    string Фио
    string Отдел
    data ЗаказатьТовар()
}

class "Работник склада"{
    string ФИО
    int Стаж
    data ФормированиеОтчета()
    data ПриемТовара()
}

class Продавец{
    string ФИО
    int Стаж
    data ВыдачаНакладной()
}

Кассир --|> Персонал
Продавец --|> Персонал
"Работник склада" --|> Склад
Директор --|> Руководство
Магазин ..> Руководство
Персонал ..> Руководство
Продавец ..> Склад
Кассир --> Магазин: Работа
Продавец --> Магазин: Работа
"Работник склада" --> Магазин: Работа

@enduml