@startuml lb5

actor Покупатель
actor Продавец
actor Кассир
actor Складовщик
participant Товар
participant Склад

activate Покупатель
activate Продавец
Покупатель -> Продавец:Принять заказ
deactivate Покупатель
activate Складовщик
Продавец -> Складовщик:Попросить товар
deactivate Продавец
activate Склад
Складовщик -> Склад:Найти товар
activate Товар
Товар -> Складовщик:Товар найден
destroy Склад
activate Продавец
Складовщик -> Продавец:Передача товара
deactivate Складовщик
activate Кассир
activate Покупатель
Кассир->Покупатель:Выдать счет
Покупатель -> Кассир:Оплатить счет
Кассир->Продавец:Принять платеж
Продавец -> Покупатель:Выдать товар

@enduml