@startuml

state ОплатаТовара{
    [*] --> ПолучениеДенег
    ПолучениеДенег --> ОформлениеЧека:Подготовка чека
}


state Отчетность{
    [*] --> ЗаказТовара
    ЗаказТовара --> ФормированиеОтчета:Учет товара\nна складе

}


state ФормированиеКорзины{
    [*] --> ВыборТовара
    ВыборТовара --> СписокПокупок:Занесение в\nкорзину
    СписокПокупок --> ВыборТовара:Требуется еще\nтовар
}

state ВыдачаТовара{
    [*] --> ВыдачаТоваров
    ВыдачаТоваров --> ВыдачаТоваров:Еще не все\nвыданы
} 

ОплатаТовара --> ВыдачаТовара
Отчетность --> ФормированиеКорзины:Информация\nо товаре
ФормированиеКорзины --> ОплатаТовара:Передача денег\nза товар
ФормированиеКорзины --> Отчетность:Проверка товара\nна складе
ВыдачаТовара --> [*]